on:
  workflow_dispatch:

name: Codecov

jobs:
  # codecov collects code coverage data from the rust tests, python snippets and python test suite.
  # This is done using cargo-llvm-cov, which is a wrapper around llvm-cov.
  codecov:
    name: Collect code coverage data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: sudo apt-get update && sudo apt-get -y install lcov
      - name: Run cargo-llvm-cov with tests.
        run: cargo llvm-cov --no-report
        continue-on-error: true
      - name: Prepare code coverage data
        run: cargo llvm-cov report --lcov --output-path='codecov.lcov'
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./codecov.lcov
